language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: DEFa4pgzc5JEXaE+9A5YhB8qzNwd3YMb4btXBe5uaZ+OfGM1RgSluvhSjaAQHr9dPsUGQe7FX1u56V4RvGAeveQrEMtwHfbPP+JhlASq6ufTtwTIUZopE6vzlxfbO2hXkrHu2deacxvtePvDO0OxLZMoWX/s8diB0TaloPia2JA=
  app: thawing-chamber-5618
  on:
    repo: meguro-cd/idobata-chan
